backend:
  name: git-gateway
  branch: main # O branch que você está usando

media_folder: "uploads" # Pasta para armazenar arquivos de mídia
public_folder: "/uploads" # Caminho público

collections:
  - name: "produtos" # Nome da coleção
    label: "Produtos"
    folder: "produtos" # Pasta onde os arquivos de produtos estão
    create: true
    fields:
      - { label: "Nome", name: "nome", widget: "string" }
      - { label: "Descrição", name: "descricao", widget: "text" }
      - { label: "Imagem", name: "imagem", widget: "image" }
